apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: {{ .Release.Namespace }}
data:
  nfs-server: "{{ .Values.nfs-server }}"
  nfs-path: "{{ .Values.nfs-server}}"
  storage-class: "{{ .Values.storage-class }}"